// Copyright (c) 2024 The Brave Authors. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// you can obtain one at https://mozilla.org/MPL/2.0/.

import {PrefsMixin} from '/shared/settings/prefs/prefs_mixin.js'
import {I18nMixin} from 'chrome://resources/cr_elements/i18n_mixin.js'
import {WebUiListenerMixin} from 'chrome://resources/cr_elements/web_ui_listener_mixin.js'
import {PolymerElement} from 'chrome://resources/polymer/v3_0/polymer/polymer_bundled.min.js'

import {loadTimeData} from '../i18n_setup.js'
import {RouteObserverMixin} from '../router.js'

import {
  BraveParentalFreedomBrowserProxy,
  BraveParentalFreedomBrowserProxyImpl,
  PairingSession
} from './brave_parental_freedom_browser_proxy.js'

import {getTemplate} from './brave_parental_freedom_subpage.html.js'

const SettingsBraveParentalFreedomPageBase =
  I18nMixin(RouteObserverMixin(WebUiListenerMixin(PrefsMixin(PolymerElement))))

/**
 * 'settings-brave-parental-freedom-subpage' is the settings page containing
 * Brave's Allow2 parental controls settings.
 */
class SettingsBraveParentalFreedomPage
  extends SettingsBraveParentalFreedomPageBase {
  static get is() {
    return 'settings-brave-parental-freedom-subpage'
  }

  static get template() {
    return getTemplate()
  }

  static get properties() {
    return {
      isPaired_: {
        type: Boolean,
        value: false,
      },

      pairingSession_: {
        type: Object,
        value: null,
      },

      pollingInterval_: {
        type: Number,
        value: null,
      },
    }
  }

  private declare isPaired_: boolean
  private declare pairingSession_: PairingSession | null
  private declare pollingInterval_: number | null

  private browserProxy_: BraveParentalFreedomBrowserProxy =
    BraveParentalFreedomBrowserProxyImpl.getInstance()

  override ready() {
    super.ready()

    if (loadTimeData.getBoolean('shouldExposeElementsForTesting')) {
      window.testing = window.testing || {}
      window.testing.parentalFreedomSubpage = this.shadowRoot
    }

    // Load initial pairing state
    this.loadPairingStatus_()

    // Listen for state changes from C++
    this.addWebUiListener('pairing-state-changed', () => {
      this.loadPairingStatus_()
    })
  }

  override currentRouteChanged() {
    // Refresh status when navigating to this page
    this.loadPairingStatus_()
  }

  override disconnectedCallback() {
    super.disconnectedCallback()
    this.stopPolling_()
  }

  private async loadPairingStatus_() {
    const status = await this.browserProxy_.getPairingStatus()
    this.isPaired_ = status.isPaired
  }

  private async onStartPairing_() {
    const deviceName = 'Brave Browser'
    // Use QR pairing to get a QR code image from the C++ backend
    const result = await this.browserProxy_.initQRPairing(deviceName)

    if (result.success) {
      this.pairingSession_ = result
      this.startPolling_()
      // Display QR code generated by C++ backend
      this.updateQRCode_()
    } else {
      console.error('Failed to start pairing:', result.error)
    }
  }

  private updateQRCode_() {
    if (!this.pairingSession_) {
      return
    }
    const qrCodeImg = this.shadowRoot?.getElementById('qrCodeImage') as HTMLImageElement
    if (qrCodeImg && this.pairingSession_.qrCodeUrl) {
      // Use the QR code image generated by the C++ backend (base64-encoded PNG)
      qrCodeImg.src = this.pairingSession_.qrCodeUrl
    }
  }

  private onCancelPairing_() {
    if (this.pairingSession_) {
      this.browserProxy_.cancelPairing(this.pairingSession_.sessionId)
      this.pairingSession_ = null
      this.stopPolling_()
    }
  }

  private startPolling_() {
    this.stopPolling_()
    this.pollingInterval_ = window.setInterval(() => {
      this.checkPairingStatus_()
    }, 3000)
  }

  private stopPolling_() {
    if (this.pollingInterval_ !== null) {
      window.clearInterval(this.pollingInterval_)
      this.pollingInterval_ = null
    }
  }

  private async checkPairingStatus_() {
    if (!this.pairingSession_) {
      return
    }

    const result = await this.browserProxy_.checkPairingStatus(
      this.pairingSession_.sessionId
    )

    if (result.completed) {
      this.stopPolling_()
      this.pairingSession_ = null

      if (result.success) {
        this.loadPairingStatus_()
      } else {
        console.error('Pairing failed:', result.error)
      }
    }
  }

  private getWebPairingUrl_(session: PairingSession | null): string {
    if (!session) {
      return 'https://app.allow2.com/pair'
    }
    // Use the server-provided URL which includes all pairing parameters
    // This URL is also encoded in the QR code for Universal/App Link deep linking
    if (session.webPairingUrl) {
      return session.webPairingUrl
    }
    // Fallback: generate URL client-side if not provided by server
    const params = new URLSearchParams({
      sessionId: session.sessionId,
      pin: session.pinCode,
      deviceName: 'Brave Browser'
    })
    return `https://app.allow2.com/pair?${params.toString()}`
  }
}

customElements.define(
  SettingsBraveParentalFreedomPage.is,
  SettingsBraveParentalFreedomPage
)
